from growwapi import GrowwAPI

from call_spread_time import CallSpreadTrade
from constant import call_spread, put_spread
from put_spread_time import PutSpreadTrade
from utils import Utils

if __name__ == '__main__':
    access_token = "eyJraWQiOiJaTUtjVXciLCJhbGciOiJFUzI1NiJ9.eyJleHAiOjE3NjIxMjk4MDAsImlhdCI6MTc2MjA1ODA5MCwibmJmIjoxNzYyMDU4MDkwLCJzdWIiOiJ7XCJ0b2tlblJlZklkXCI6XCJmNGUzMmMxMS02ZjVmLTQ5MTYtYmVhNy0xNzIyNDkyN2JhOGRcIixcInZlbmRvckludGVncmF0aW9uS2V5XCI6XCJlMzFmZjIzYjA4NmI0MDZjODg3NGIyZjZkODQ5NTMxM1wiLFwidXNlckFjY291bnRJZFwiOlwiNTY1NmU1ODEtZmI4NC00OGYyLTk5NjctYWExODQ2MmQ4ZTdiXCIsXCJkZXZpY2VJZFwiOlwiY2RlZmFlODMtNjQ2Yy01MjU1LThmMmUtNzYzY2RkN2Y2ZWZhXCIsXCJzZXNzaW9uSWRcIjpcIjE1MDAyNmE3LWZjNDMtNGFhYS1hMzA0LTI3ZTI1ZTNmOTZlZlwiLFwiYWRkaXRpb25hbERhdGFcIjpcIno1NC9NZzltdjE2WXdmb0gvS0EwYkVzQmpMRHhxV29paXlMK0ZHb0N6TU5STkczdTlLa2pWZDNoWjU1ZStNZERhWXBOVi9UOUxIRmtQejFFQisybTdRPT1cIixcInJvbGVcIjpcIm9yZGVyLWJhc2ljLGxpdmVfZGF0YS1iYXNpYyxub25fdHJhZGluZy1iYXNpYyxvcmRlcl9yZWFkX29ubHktYmFzaWMsYmFja190ZXN0XCIsXCJzb3VyY2VJcEFkZHJlc3NcIjpcIjEwMy4yMDYuMTE0LjcyLDE3Mi42OS44Ny44NSwzNS4yNDEuMjMuMTIzXCIsXCJ0d29GYUV4cGlyeVRzXCI6MTc2MjEyOTgwMDAwMH0iLCJpc3MiOiJhcGV4LWF1dGgtcHJvZC1hcHAifQ.AraQx96yAf9Qg1Ic6ubrrj3TxdBOFH5ciqC_Wm0bHjABlzDrWST_AOdnudIkG6GrCzkgirMBjWB_jPerytJsAQ"
    groww = GrowwAPI(access_token)
    
    if call_spread:
        CallSpreadTrade(groww).call_spread()
    if put_spread:
        PutSpreadTrade(groww).put_spread()

    utils = Utils(groww)
    utils.close_all_fno_trades()
